#!/bin/bash
cd ..
mkdir -p "data/sub-$1/ses-$2"
cp --target-directory="sub-$1/ses-$2" assets/template-labnotebook.tsv assets/template-participantform.tsv
mv "sub-$1/ses-$2/template-labnotebook.tsv" "sub-$1/ses-$2/sub-$1_ses-$2_labnotebook.tsv"
mv "sub-$1/ses-$2/template-participantform.tsv" "sub-$1/ses-$2/sub-$1_ses-$2_participantform.tsv"
gedit "sub-$1/ses-$2/sub-$1_ses-$2_participantform.tsv"
gedit "sub-$1/ses-$2/sub-$1_ses-$2_labnotebook.tsv"
